# Generated by Django 2.2.2 on 2019-06-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190630_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(upload_to='posts/static/posts'),
        ),
    ]
